### ISSUE TITLE
Tom Schoenrock-Rossiter code review 

### ISSUE THREAD

**Issue by Tsrockross** [earthlab-education/ea-lidar-uncertainty-review#33]
#20 

@S-Kur 

Really nice job on the code, I think I picked up a few tiny things but it was really clean and concise.

**Review Checklist**

CI Checks
The notebook runs from start to finish on all operating systems:
[x] Mac
[x] Windows
[x] Linux

**Reproducibility**
[x] Are the data downloaded in the code
[x] Are paths created to ensure they work on all operating systems (using os.path.join)
[x] Are comments used to clarify the contents of the code that can’t be clarified using expressive variable and function names alone? (not too many comments - just enough)
[x] Does the notebook run from start to finish?

**PEP 8 standards & Code Readability**
Functions
[x] Do functions follow PEP 8 format conventions?
[x] Are function docstrings clear (all inputs and outputs clearly described and defined)
[x] Are function names expressive (the name describes what the function does)?
[x] Are functions easy to understand and read?
[x] How many tasks does each function do? (ideally a function does one thing well).

**Package imports**
[x] Are standard modules (those included with the base python install) vs. third party (related but externally developed tools) import groups correct with appropriate spacing in between each group?
[x] Are variable names throughout the code, expressive?
**Your code was very easy to read and follow because of your well-named variables!
[x] Is the code overall easy to understand and read? Are there things that would make it more clear / cleaner?

**DRY Code**
[x] Are segments of code repeated in the file or is the code DRY?
[x] Are loops used to optimize DRY code?
[x] Are functions used to optimize DRY code?
[x] Are there any areas that could be potentially improved (you can suggest improvements OR you can just highlight parts of the code where you suspect it could be cleaner / more efficient.

**Novel Approaches to Problem solving**
[x] Highlight any novel approaches to completing the assignment.
**I hadn't seen the code you used for plotting before, it works really well

**Comment by S-Kur** [comment]
@Tsrockross Thank you for the review!
