### ISSUE TITLE
@csandberg303 minor suggestion to ensure functionality

### ISSUE THREAD

**Issue by esgeo** [earthlab-education/ea-lidar-uncertainty-review#42]
@csandberg303 

Please see the comments on the code in your PR #28  

Review Checklist
CI Checks
 
The notebook runs from start to finish on all operating systems:

 

- [X] Mac
- [X] Windows
- [X] Linux

Reproducibility
- [X]  Are the data downloaded in the code
- [X]  Are paths created to ensure they work on all operating systems (using os.path.join) (https://github.com/earthlab-education/ea-2021-ndvi-automation-review/pull/28#discussion_r816357501)
- [X] Are comments used to clarify the contents of the code that can’t be clarified using expressive variable and function names alone? (not too many comments - just enough)
- [X] Does the notebook run from start to finish?

PEP 8 standards & Code Readability
Functions
- [X] Do functions follow PEP 8 format conventions?
- [X] Are function docstrings clear (all inputs and outputs clearly described and defined)
- [X] Are function names expressive (the name describes what the function does)?
- [X] Are functions easy to understand and read?
- [X] How many tasks does each function do? (ideally a function does one thing well). _One of the functions: `process_single_scene` is quite multimodal_

Package imports
- [X] Are standard modules (those included with the base python install) vs. third party (related but externally developed tools) import groups correct with appropriate spacing in between each group? _One or two modules included but not used_https://github.com/earthlab-education/ea-2021-ndvi-automation-review/pull/28#discussion_r816426172
- [X] Are variable names throughout the code, expressive?
 Suggest changes if not, highlight what was done well
- [X] Is the code overall easy to understand and read? Are there things that would make it more clear / cleaner?
DRY Code
- [X]  Are segments of code repeated in the file or is the code DRY?
- [X] Are loops used to optimize DRY code?
- [X] Are functions used to optimize DRY code?
- [x] Are there any areas that could be potentially improved (you can suggest improvements OR you can just highlight parts of the code where you suspect it could be cleaner / more efficient. https://github.com/earthlab-education/ea-2021-ndvi-automation-review/pull/28#discussion_r816412776
Novel Approaches to Problem solving
- [X] Highlight any novel approaches to completing the assignment.
_I'm somewhat torn because I think your function that was multimodal (and therefore frowned upon) was also really powerful!_
https://github.com/earthlab-education/ea-2021-ndvi-automation-review/pull/28#discussion_r816412776

Great work, reviewing your code was enjoyable and easy, and was even moreso because Mitchell had already been through it before me!

**Comment by csandberg303** [comment]
Thank you Eric!  I was fun to have two reviewers, and I thought you had a bit of a complex review when you were commenting on Mitchell's comments, as well as my original code.  I appreciate your observations I'm better off because of it.
