### ISSUE TITLE
NDVI review 

### ISSUE THREAD

**Issue by LManak** [earthlab-education/ea-lidar-uncertainty-review#44]
@esgeo here are some notes and my review checklist for your pull request #29 !

Great work! Clean code and it all runs well for me. One thing I would look at is reducing some language in your docstrings. I think specifically the first description line should only be one line long, however I can't remember specifically.  Especially for the function "mask_crop_ndvi". 

Review Checklist
CI Checks

- [ X]  The notebook runs from start to finish on all operating systems:

 Mac
 Windows
 Linux
Reproducibility
 

- [ X] Are the data downloaded in the code
- [X ] Are paths created to ensure they work on all operating systems (using os.path.join)
- [ X] Are comments used to clarify the contents of the code that can’t be clarified using expressive variable and function names alone? (not too many comments - just enough)
- [ X] Does the notebook run from start to finish?
PEP 8 standards & Code Readability
Functions
- [ ] Do functions follow PEP 8 format conventions?  ** I think here we need to review the first line & initial description length.
- [ X] Are function docstrings clear (all inputs and outputs clearly described and defined)
- [X ] Are function names expressive (the name describes what the function does)?
- [X ] Are functions easy to understand and read?
- [ ] How many tasks does each function do? (ideally a function does one thing well).
Package imports
- [ X] Are standard modules (those included with the base python install) vs. third party (related but externally developed tools) import groups correct with appropriate spacing in between each group?
- [ X]  Are variable names throughout the code, expressive?
 Suggest changes if not, highlight what was done well
- [ X] Is the code overall easy to understand and read? Are there things that would make it more clear / cleaner?  **some of the lines extended the PEP 8 line length, and I think the descriptions were good, however I wonder if you could combine some code lines and have the commented section describe a few things instead of every line. 
DRY Code. 
- [X ] Are segments of code repeated in the file or is the code DRY?
- [ X] Are loops used to optimize DRY code?
- [ X] Are functions used to optimize DRY code?
- [ ] Are there any areas that could be potentially improved (you can suggest improvements OR you can just highlight parts of the code where you suspect it could be cleaner / more efficient.
Novel Approaches to Problem solving
 Highlight any novel approaches to completing the assignment.
** great work making the graph your own! I really like how you changed the date format. I really like how descriptive your variables are, and how you included a lot of description in the comments. I think the thing that might need the most review is the first line in your doc-strings. I might need to review this, but I feel like I remember that needs to be one-line long and pretty brief. Also there were a few lines that seemed to be too long for PEP 8. Otherwise, great work!

**Comment by esgeo** [comment]
@LManak Thank you Leah,  I made the change you suggested to the doc string in the second function and tried to break my code lines where they seemed too long. I will be pushing the new versions momentarily.
